neos/neos-development-distribution

- composer.json
The version number syntax is wrong, dash and dot are mixed up.
> [BUGFIX] Fix syntax of typo3/setup composer dependency

- Build/create-changelog.sh
Instead of '[TASK]' it now uses 'TASK:'
> TASK: Make create-changelog.sh use new commit subject style

- composer.json
The stability flag is enough, since Neos itself specifies the correct branch.
> TASK: Relax version constraint for Flow

- Build/set-dependencies.sh
This change adjusts the set-dependencies.sh script to the
new Composer package names used by Neos 3.0 and later.
Resolves #24
> TASK: Adjust set-dependencies.sh to Neos 3.0

- crowdin.json
This is ready-to-use with our Crowdin tooling, it only needs the API key
in an environment variable named `CROWDIN_API_KEY`.
And of course the `crowdin-cli` binary.
> TASK: Add crowdin.json configuration file

- composer.json
It does not work with the required PHP 7 anyway.
> TASK: No longer require PhpUnit 4.8

- Build/create-changelog.sh
When building a changelog, the script would exit if PR details could
not be fetched. Since this can happen due to "malformed" commit messages
the script will now simply continue with the next change.
This makes sure a changelog is generated and not skipped completely,
just because PR details cannot be fetched.
> TASK: Ignore errors when fetching PR details

- Build/install-composer.sh
- Build/sync-crowdin.sh
- crowdin.json
This updates the crowdin.json file for the 2.3 branch and adds a shell
script to sync sources and translations with crowdin.
That shell script basically contains the code that was in the job on
the Jenkins server as a build step.
A script to install composer is added as well, it can be used by other
scripts, too.
> TASK: Set up crowdin integration (again)

- composer.json
This change raises the phpunit requirement to v8.1. This might be breaking for you as phpunit introduced return types on methods like `public setUp(): void` as well as `public tearDown(): void`. PHPUnit also deprecated a lot of methods. You might find [here](https://thephp.cc/news/2019/02/help-my-tests-stopped-working) some more background information about replacements for your assertions.
> !!! FEATURE: Raise phpunit to v8.1

- composer.json
The latest changes in Neos.Form master will break the php 7.0 tests for Neos 3.3 as they rely on php 7.1
By pinning the form version to 4.2 we make sure to get a php 7 compatible version.
> TASK: Require Neos.Form 4.2.x-dev for development distribution 3.3

- Build/set-dependencies.sh
The lock package is gone as of https://github.com/neos/flow-development-collection/pull/1771
> TASK: Remove handling of neos/utility-lock from set-dependencies.sh

- composer.json
Add neos/fusion-form and neos/fusion-afx as dependencies to the development distribution.
This will make working on those packages easier until they will be incorporated into the dev-collection.
> TASK: Require fusion-form and fusion-afx in dev distribution

- composer.json
This aligns the development distribution with the base distribution.
All packages in DistributionPackages are registered in the composer file as a local repository and can be required.
> BUGFIX: Add DistributionPackages folder

- Build/update-references.sh
Since docs updates don't need to be tested, this is a no-risk way
of hopefully reducing build time use on Travis.
See https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
> TASK: Skip Travis CI on references update

- Build/sync-crowdin.sh
Since XLIFF updates don't need to be tested, this is a no-risk way
of hopefully reducing build time use on Travis.
See https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
> TASK: Skip Travis CI on translations update

- composer.json
Needed because dev-master of behat requires PHP > 7.1
> TASK: Adjust neos/behat version

- composer.json
To keep in sync with https://github.com/neos/flow-development-distribution/commits/6.0/composer.json
Note: If we add psalm checks to the Neos codebase, the scripts would need to change and then we need to take care to not have a confusing setup
> TASK: Require vimeo/psalm and add test scripts

- Build/set-dependencies.sh
See https://github.com/neos/neos-base-distribution/pull/52#pullrequestreview-649289822
Note: This probably also needs an automatic tagging of a release for every x.x.0 version of Flow (see neos/flow-development-distribution#67)
> TASK: Update neos/behat and buildessentials version

- Build/create-branch.sh
- Build/set-dependencies.sh
- Build/tag-release.sh
Since version 4.3 Neos Demo had a separate version number from Neos but since Neos 7 Neos.Demo and Neos are in sync again. This change adds the creating of branches and releases for Neos.Demo to the release job again to ease the job of the releaser managers a little.
Note: The now reverted changes were added here https://github.com/neos/neos-development-distribution/pull/47
> TASK: Add tagging of Neos.Demo to the release scripts again

- composer.json
Since this is the development distribution for neos composer should install all neos packages from source.
Since quite some packages in the flowpack namespace are maintained by neos team members and some are
even installed in a default neos it makes our life easier to install packages from source in the development distribution aswell.
See https://getcomposer.org/doc/06-config.md#preferred-install
Resolves: #70
> TASK: Prefer installing of neos and flowpack packages from source

- composer.json
Under some (unknown) circumstances composer will try to install a X.Y.x-dev version instead of dev-master in builds (see https://github.com/neos/neos-development-collection/pull/3332#issuecomment-895905592). One way to prevent that would be to adjust the build script to require "dev-master" of the flow collection like is currently done for the (locally checked out) neos collection. Another is to adjust the require already in the master branch of the distribution here, since on release/branching off the two versions are adjusted to match the branch (see https://github.com/neos/neos-development-distribution/blob/7.1/composer.json#L19-L20).
> TASK: Require strict dev-master of the dev-collections

- Build/set-dependencies.sh
- composer.json
Add `./flow welcome` as post create project command to the composer json which shows the required steps to setup neos by cli.
Additionally this adds neos/cli-setup to the set dependencies script to ensure the bae distribution requires the matching version.
Relates: https://github.com/neos/neos-development-collection/pull/3505, https://github.com/neos/neos-development-collection/issues/3506
> TASK: Show welcome message after composer create-project and adjust set-dependencies script

- Build/release.sh
This is done by checking if the released version string ends with ".0" and if so, invokes the `create-releasenotes.sh` script
> TASK: Automatically generate release notes when creating a minor or major release
